import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, copyFile, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { pagesOf, blanksOf } from "../vps/docx-render/map.mjs";

const run = promisify(execFile);
const here = dirname(fileURLToPath(import.meta.url));
const FORMS = join(here, "..", "src", "forms");

const LINES = {
  witness: ["WITNESS", "POSITION & SITE", "NAME FOR WHOM TESTIMONY IS FOR", "RELATIONSHIP WITH CANDIDATE"],
  observation: ["ASSESSOR", "POSITION & SITE", "NAME OF CANDIDATE OBSERVED", "RELATIONSHIP WITH CANDIDATE"],
  knowledge: ["ASSESSOR", "POSITION & SITE", "CANDIDATE QUESTIONED", "RELATIONSHIP WITH CANDIDATE"],
  feedback: ["ASSESSOR", "POSITION & SITE", "CANDIDATE", "RELATIONSHIP WITH CANDIDATE"],
};

const kinds = (await readdir(FORMS)).filter((f) => f.endsWith(".docx"));
const dir = await mkdtemp(join(tmpdir(), "blank-"));
const map = {};
try {
  for (const file of kinds) await copyFile(join(FORMS, file), join(dir, file));
  await run(
    "soffice",
    [`-env:UserInstallation=file://${join(dir, "profile")}`, "--headless", "--norestore",
     "--convert-to", "pdf", "--outdir", dir, ...kinds.map((f) => join(dir, f))],
    { timeout: 180_000 },
  );
  for (const file of kinds) {
    const kind = file.replace(/\.docx$/, "");
    const made = join(dir, `${kind}.pdf`);
    const target = join(FORMS, `${kind}.pdf`);
    await copyFile(made, target);

    const pages = await pagesOf(await readFile(made));
    const { fields, boxes } = blanksOf(pages, LINES[kind] || []);
    map[kind] = { fields, boxes };
    const { size } = await stat(target);
    console.log(
      `${kind.padEnd(14)} ${String(Math.round(size / 1024)).padStart(3)}KB · ${pages.length} pages · ` +
        `${fields.length}/${(LINES[kind] || []).length} lines · ${boxes.length} box${boxes.length === 1 ? "" : "es"}`,
    );
  }
  await writeFile(
    join(FORMS, "blanks.js"),
    `/* Generated by scripts/blank-pages.mjs from the blank forms. Do not edit.\n` +
      `   Where each form's blanks sit, as fractions of the page. Regenerate\n` +
      `   whenever a form changes. */\nexport const BLANKS = ${JSON.stringify(map, null, 1)};\n`,
  );
  console.log("-> src/forms/blanks.js");
} finally {
  await rm(dir, { recursive: true, force: true }).catch(() => {});
}
