import { readFile, writeFile, readdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { strFromU8, unzipSync } from "fflate";

const here = dirname(fileURLToPath(import.meta.url));
const FORMS = join(here, "..", "src", "forms");
const OUT = join(here, "..", "api", "_printed.js");

const entities = (s) =>
  s.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'").replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)))
    .replace(/&amp;/g, "&");

function wordsOf(bytes) {
  const zip = unzipSync(new Uint8Array(bytes));
  let out = "";
  for (const part of ["word/document.xml", "word/header1.xml", "word/header2.xml",
                      "word/header3.xml", "word/footer1.xml", "word/footer2.xml", "word/footer3.xml"]) {
    if (!zip[part]) continue;
    const xml = strFromU8(zip[part]).replace(/<w:tab[^>]*\/>/g, "\t").replace(/<\/w:p>/g, "\n");
    out += entities(xml.replace(/<[^>]+>/g, "")) + "\n";
  }
  return out;
}

const tidy = (line) => line.split(/\s+/).filter(Boolean).join(" ");

const printed = new Set();
for (const file of (await readdir(FORMS)).filter((f) => f.endsWith(".docx"))) {
  for (const line of wordsOf(await readFile(join(FORMS, file))).split("\n")) {
    const t = tidy(line);
    if (t.length >= 3) printed.add(t);
  }
}

const lines = [...printed].sort();
const flat = (t) => t.toLowerCase().replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim();
const blob = lines.map(flat).join(" ");

await writeFile(OUT, `/* Generated by scripts/boilerplate.mjs from the blank forms. Do not edit.
   Every line the company's own forms print, so indexing can tell furniture
   from what a person wrote. Regenerate whenever a form changes. */
export const PRINTED = new Set(${JSON.stringify(lines, null, 1)});

/** Everything the forms print, flattened, for text read off a scan. */
export const PRINTED_RUN = ${JSON.stringify(blob)};

/** Every word the forms print, for judging a line too short to contain. */
export const PRINTED_WORDS = new Set(PRINTED_RUN.split(" "));

/** The same flattening the run was built with. */
export const flatten = (t) =>
  String(t).toLowerCase().replace(/[^a-z0-9]+/g, " ").replace(/\\s+/g, " ").trim();
`);
console.log(`${lines.length} printed lines -> api/_printed.js`);
