import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const FORMS = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "forms");
const OUT = join(FORMS, "published.js");
const BASE = (process.env.SUPABASE_URL || "http://127.0.0.1:8000").replace(/\/+$/, "");
const SERVICE = process.env.SUPABASE_SERVICE_ROLE_KEY || "";

const write = (forms, at, why) => {
  writeFileSync(OUT, `/* Generated by scripts/forms-pull.mjs. Do not edit.
   The forms as they were published when the copy that runs from a folder was
   built — it has no server to ask, so it carries them. Empty when nothing has
   been published beyond the company's own, which are already inside the file.
   ${why} */
export const PACKED_AT = ${JSON.stringify(at)};
export const PACKED = ${JSON.stringify(forms, null, 1)};
`);
};

const today = new Date().toISOString().slice(0, 10);
if (!SERVICE) {
  write({}, today, "No service key here, so nothing could be asked for.");
  console.log("no service key (SUPABASE_SERVICE_ROLE_KEY) — packed nothing, the forms compiled in stand");
  process.exit(0);
}

const rest = async (path) => {
  const res = await fetch(`${BASE}/rest/v1/${path}`, {
    headers: { apikey: SERVICE, authorization: `Bearer ${SERVICE}` },
  });
  if (!res.ok) throw new Error(`${res.status} ${(await res.text()).slice(0, 120)}`);
  return res.json();
};

const rows = await rest(
  "offshore_report_templates_live?select=kind,offshore_report_templates(version,sha256,path,anchors,blanks)",
).catch((e) => {
  console.log(`could not reach the store (${e.message.slice(0, 60)}) — packed nothing`);
  return null;
});
if (!rows) { write({}, today, "The store could not be reached."); process.exit(0); }

const SHEETS = ["sed"];

const packed = {};
for (const row of rows) {
  const t = row.offshore_report_templates;
  if (!t || t.version === 0 || !t.path) continue;
  if (SHEETS.includes(row.kind)) { console.log(`${row.kind.padEnd(12)} is a workbook — not packed`); continue; }
  const file = await fetch(`${BASE}/storage/v1/object/offshore-report-templates/${encodeURI(t.path)}`, {
    headers: { apikey: SERVICE, authorization: `Bearer ${SERVICE}` },
  });
  if (!file.ok) { console.log(`${row.kind}: could not be fetched, skipped`); continue; }
  const bytes = Buffer.from(await file.arrayBuffer());
  packed[row.kind] = {
    version: t.version,
    sha256: t.sha256,
    anchors: t.anchors || {},
    blanks: t.blanks || {},
    bytes: bytes.toString("base64"),
  };
  console.log(`${row.kind.padEnd(12)} v${t.version} packed · ${(bytes.length / 1024).toFixed(0)}KB`);
}
write(packed, today, Object.keys(packed).length ? "" : "Every form is the company's own.");
console.log(
  Object.keys(packed).length
    ? `\npacked ${Object.keys(packed).length} published form(s), as of ${today}`
    : `\nevery form is the company's own — nothing to pack, as of ${today}`,
);
