export const PRINTED = new Set([
 "(Block Capitals — to be completed by the assessor at the end of each trip)",
 "(Block Capitals — to be completed by the assessor)",
 "(Block Capitals — to be completed by the witness)",
 "5981700330200WT00",
 "A mark of 1 or 2 must be explained in the comments column, with what is needed to improve.",
 "A signed record, written by an assessor, of a task the candidate was seen to perform. The assessor must have been present for the work described.",
 "ADDITIONAL ASSESSOR SIGNATURE: ………………………………………………",
 "ASSESSOR SIGNATURE: ………………………………………………………………………………",
 "ASSESSOR:",
 "AUTHOR SIGNATURE: ………………………………………………………………………………",
 "An assessor with the knowledge and experience to judge the answers against the standard.",
 "Anyone technically competent in the work described who saw the candidate do it — a supervisor, a senior technician or a client representative. The witness does not need to be an assessor.",
 "Assessee Comments",
 "Assessee Name",
 "Assessee Signature",
 "Assessment Outcome",
 "Assessor Comments",
 "Assessor Feedback Form",
 "Assessor Name",
 "Assessor Observation Report",
 "Assessor Signature",
 "Assessor's comments of candidate performance in relation to the evidence presented:",
 "Attendance and Punctuality",
 "CANDIDATE QUESTIONED:",
 "CANDIDATE SIGNATURE: ………………………………………………………………………………",
 "CANDIDATE:",
 "Candidate's comments in relation to the CAAP scheme:",
 "Comments",
 "Communication",
 "Competency Assurance and Assessment Programme",
 "Complete the form in the last days of the trip, with the assessee present, and discuss every mark given.",
 "Crew Performance Programme",
 "Crewing Department Name",
 "Criteria",
 "DATE: ……………………………………………………",
 "Date",
 "Date Received",
 "Date of Assessment from/To",
 "Decision Making",
 "Describe in the box below the work you observed and the parts of the standard it covered (please see reverse for guidance notes).",
 "Encourage candidates to judge their own work against the standard, help them see how day-to-day jobs can be used as evidence, and adapt the level of support to each person.",
 "English Language Proficiency (Verbal and Written)",
 "Essential Knowledge Record",
 "GUIDANCE NOTES FOR ASSESSORS GIVING FEEDBACK",
 "GUIDANCE NOTES FOR THE COMPLETION OF A WITNESS TESTIMONY",
 "GUIDANCE NOTES FOR THE COMPLETION OF AN ESSENTIAL KNOWLEDGE RECORD",
 "GUIDANCE NOTES FOR THE COMPLETION OF AN OBSERVATION REPORT",
 "Guidance Notes; completing the trip assessment",
 "Hand the signed form to the onshore crewing department within seven days of the end of the trip.",
 "How is it used?",
 "How should they be recorded?",
 "How will it be used?",
 "I confirm I was present and observed the work described above.",
 "I confirm the above is an accurate account of work I saw the candidate carry out.",
 "I have asked the candidate the following questions and their responses are recorded below (please see reverse for guidance notes).",
 "I have reviewed the evidence presented and can confirm he/she has met the required standard of the programme.",
 "I have reviewed the evidence presented and can confirm he/she has not yet met the required standard of the programme.",
 "Initiative",
 "It is fair, specific to the work that was done, and says what can be done to meet the standard where it has not yet been met. It ends with what the candidate should do next.",
 "It is filed as direct evidence of competence and cross-referenced to the standard, so that what is still outstanding can be planned.",
 "Knowledge of Role",
 "Leadership Qualities",
 "Leadership Qualities applies to supervisory positions only; otherwise write N/A.",
 "Motivation",
 "NAME FOR WHOM TESTIMONY IS FOR:",
 "NAME OF CANDIDATE OBSERVED:",
 "NORTHWIND OFFSHORE",
 "NW-CAP-001 Rev: 1 www.northwind.example Page PAGE 1 of NUMPAGES 1",
 "Northwind Offshore · Business Management System",
 "Once the task has been completed, at an agreed time and place, with the assessor prepared.",
 "Onshore Crewing Department",
 "POSITION & SITE:",
 "Please give your testimony in the box below: what work was done, where, when and with which equipment (please see reverse for guidance notes).",
 "Position/Job Title",
 "Q1:",
 "Q2:",
 "Q3:",
 "Q4:",
 "Quality of Work",
 "RELATIONSHIP WITH CANDIDATE:",
 "Rate each criterion by marking one column: 1 Unsatisfactory · 2 Requires Improvement · 3 On Target · 4 Above Target · 5 Exceptional",
 "Safety Behaviour and Awareness",
 "Signature",
 "Signatures",
 "Supporting the candidate",
 "Teamwork Skills",
 "Technical and Practical Ability",
 "The candidate presents the testimony to an assessor as evidence against the competency standard. The assessor decides whether it is sufficient, and may ask for more.",
 "To confirm that the candidate understands why a task is done the way it is, and what they would do if conditions changed — knowledge that watching the task alone does not show.",
 "Trip Assessment Form",
 "WITNESS:",
 "WT00",
 "What is an observation report?",
 "What makes feedback useful?",
 "What must it include?",
 "What should the testimony say?",
 "What task was carried out, where and when it happened, which equipment and procedures were used, and how the candidate performed. Describe what you saw rather than what you expect.",
 "When should feedback be given?",
 "Where a candidate has more than one assessor, each additional assessor signs below.",
 "Where and when the task took place, who else was involved, which equipment and procedures were used, and how the candidate's performance compared with the standard.",
 "Who can ask them?",
 "Who can give a witness testimony?",
 "Why ask essential knowledge questions?",
 "Witness Testimony",
 "Workscope",
 "Worksite/Vessel",
 "Write each question and the answer given, in the candidate's own words. Verbal questions are recorded in writing at the time."
]);

export const PRINTED_RUN = "block capitals to be completed by the assessor at the end of each trip block capitals to be completed by the assessor block capitals to be completed by the witness 5981700330200wt00 a mark of 1 or 2 must be explained in the comments column with what is needed to improve a signed record written by an assessor of a task the candidate was seen to perform the assessor must have been present for the work described additional assessor signature assessor signature assessor author signature an assessor with the knowledge and experience to judge the answers against the standard anyone technically competent in the work described who saw the candidate do it a supervisor a senior technician or a client representative the witness does not need to be an assessor assessee comments assessee name assessee signature assessment outcome assessor comments assessor feedback form assessor name assessor observation report assessor signature assessor s comments of candidate performance in relation to the evidence presented attendance and punctuality candidate questioned candidate signature candidate candidate s comments in relation to the caap scheme comments communication competency assurance and assessment programme complete the form in the last days of the trip with the assessee present and discuss every mark given crew performance programme crewing department name criteria date date date received date of assessment from to decision making describe in the box below the work you observed and the parts of the standard it covered please see reverse for guidance notes encourage candidates to judge their own work against the standard help them see how day to day jobs can be used as evidence and adapt the level of support to each person english language proficiency verbal and written essential knowledge record guidance notes for assessors giving feedback guidance notes for the completion of a witness testimony guidance notes for the completion of an essential knowledge record guidance notes for the completion of an observation report guidance notes completing the trip assessment hand the signed form to the onshore crewing department within seven days of the end of the trip how is it used how should they be recorded how will it be used i confirm i was present and observed the work described above i confirm the above is an accurate account of work i saw the candidate carry out i have asked the candidate the following questions and their responses are recorded below please see reverse for guidance notes i have reviewed the evidence presented and can confirm he she has met the required standard of the programme i have reviewed the evidence presented and can confirm he she has not yet met the required standard of the programme initiative it is fair specific to the work that was done and says what can be done to meet the standard where it has not yet been met it ends with what the candidate should do next it is filed as direct evidence of competence and cross referenced to the standard so that what is still outstanding can be planned knowledge of role leadership qualities leadership qualities applies to supervisory positions only otherwise write n a motivation name for whom testimony is for name of candidate observed northwind offshore nw cap 001 rev 1 www northwind example page page 1 of numpages 1 northwind offshore business management system once the task has been completed at an agreed time and place with the assessor prepared onshore crewing department position site please give your testimony in the box below what work was done where when and with which equipment please see reverse for guidance notes position job title q1 q2 q3 q4 quality of work relationship with candidate rate each criterion by marking one column 1 unsatisfactory 2 requires improvement 3 on target 4 above target 5 exceptional safety behaviour and awareness signature signatures supporting the candidate teamwork skills technical and practical ability the candidate presents the testimony to an assessor as evidence against the competency standard the assessor decides whether it is sufficient and may ask for more to confirm that the candidate understands why a task is done the way it is and what they would do if conditions changed knowledge that watching the task alone does not show trip assessment form witness wt00 what is an observation report what makes feedback useful what must it include what should the testimony say what task was carried out where and when it happened which equipment and procedures were used and how the candidate performed describe what you saw rather than what you expect when should feedback be given where a candidate has more than one assessor each additional assessor signs below where and when the task took place who else was involved which equipment and procedures were used and how the candidate s performance compared with the standard who can ask them who can give a witness testimony why ask essential knowledge questions witness testimony workscope worksite vessel write each question and the answer given in the candidate s own words verbal questions are recorded in writing at the time";

export const PRINTED_WORDS = new Set(PRINTED_RUN.split(" "));

export const flatten = (t) =>
  String(t).toLowerCase().replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim();
